### ISSUE TITLE
Suggestion: add type and ressource level for asteroid belts within a system

### ISSUE THREAD

**Issue by Brokenstorm** [themroc5/eddb.io#35] opened 2015-04-21 01:18 UTC
Would it be possible to add the reserves level and resource types for asteroid rings in the system info.
I know the reserve level is constant within a system (either Pristine, Major, Common, Low, Depleted or None if there are no asteroids belts) but there can be multiple asteroid ring types (Metallic, Metal Rich, Rocky, Icy)

Seems it would be useful with the upcoming mining revamp in 1.3

**Comment by themroc5** [comment] 2015-06-23 10:21
Duplicate of issue #29

**Closed by themroc5** 2015-06-23 10:21 UTC
